model = "gpt-5.6-sol"
model_reasoning_effort = "high"
approvals_reviewer = "user"
plan_mode_reasoning_effort = "medium"

[features]
apps = false
plugins = false
plugin_sharing = false

[otel]
environment = "vps"
log_user_prompt = true
exporter = { otlp-grpc = {
  endpoint = "http://127.0.0.1:4317"
}}
trace_exporter = { otlp-grpc = {
  endpoint = "http://127.0.0.1:4317"
}}
metrics_exporter = { otlp-grpc = {
  endpoint = "http://127.0.0.1:4317"
}}

[tui.model_availability_nux]
"gpt-5.5" = 4
"gpt-5.6-sol" = 4
